apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-miner
  namespace: mining
  labels:
    app: xmrig-miner
spec:
  replicas: 0
  selector:
    matchLabels:
      app: xmrig-miner
  template:
    metadata:
      labels:
        app: xmrig-miner
    spec:
      containers:
      - name: miner
        image: ghcr.io/murf2/xmrig.docker:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
        envFrom:
        - secretRef:
            name: xmrig-secret